language: scala

env:
  global:
  - ANDROID_HOME=$PWD/android-sdk-linux
  - ANDROID_SDK_VERSION=23.0.2
  - ANDROID_BUILD_TOOLS_VERSION=21.1.1
  - ANDROID_API_LEVEL=19
  - BINTRAY_ORG=${TRAVIS_REPO_SLUG%/*}
  - BINTRAY_PKG=${TRAVIS_REPO_SLUG#*/}
  - BINTRAY_API=https://bintray.com/api/v1
  - secure: cDgvC/r7bBIxWdAlrOixE/t/jbb+ZhOe2gvGWJg6b7MX1KnIdJZ48YL4gRs1xpKDIL1s3lrN6btGKBAkSpItajq9CV3SveQ6QQpoHJlvGvYR16fdTPmDwF7u+GAakCp9qASN+hxPhINab5FY9ugSiKn0xzcKJfXkaijx1PIQyZw=
  - secure: e6nxI2+X1261EdAYY86fkQn/xQdjYR7+tgl0WzFYb57rtmIfjC5b3WCjLYAQcsASCfgg1GzBCWEH9NaB9i+TFtZOTXNa6PpWhmvap339+6RSQWD6jJQDBM5b72F7KJO93Ys2iwlgyshTY/etYxb3XyC6TPK9PAb4ei0xn0WA2pA=

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq lib32stdc++6 lib32z1
- wget http://dl.google.com/android/android-sdk_r${ANDROID_SDK_VERSION}-linux.tgz
- tar -zxf android-sdk_r${ANDROID_SDK_VERSION}-linux.tgz
- echo yes | ${ANDROID_HOME}/tools/android update sdk --filter tools,platform-tools,build-tools-${ANDROID_BUILD_TOOLS_VERSION},android-${ANDROID_API_LEVEL},extra-android-support,extra-android-m2repository,extra-google-m2repository --no-ui --force --no-https --all > /dev/null

script: "sbt coveralls"

after_success:
- >
  test "${TRAVIS_PULL_REQUEST}" = 'false' &&
  PROJECT_VERSION=$(TERM=dumb sbt 'show version' | tail -n 1 | cut -c8- -) &&
  BINTRAY_VERSION=${PROJECT_VERSION}.${TRAVIS_BUILD_NUMBER} &&
  BINTRAY_ORG=`echo $BINTRAY_ORG | tr '[:upper:]' '[:lower:]'` &&
  ./.bintray-credentials.sh &&
  curl -H "Content-Type: application/json" -d "{ \"name\": \"${BINTRAY_VERSION}\" }" ${BINTRAY_API}/packages/${BINTRAY_ORG}/generic/${BINTRAY_PKG}/versions &&
  sbt android:package &&
  curl -T target/android-bin/${BINTRAY_PKG}-debug.apk "${BINTRAY_API}/content/${BINTRAY_ORG}/generic/${BINTRAY_PKG}/${BINTRAY_VERSION}/${BINTRAY_PKG}-${BINTRAY_VERSION}.apk;publish=1"
